<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>c8_icon.ico</ApplicationIcon> 
    <Version>1.0.5</Version>
    <AssemblyVersion>1.0.5.0</AssemblyVersion>
    <FileVersion>1.0.5.0</FileVersion>
    <Copyright>Copyright © 2026 Yagennankoz</Copyright>
    <Product>Classify8</Product>
    <Description>Windows用ファイル自動振り分けツール</Description>
  </PropertyGroup>
  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="c8_icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Help.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Classify8.Tests\**" />
    <Content Remove="Classify8.Tests\**" />
    <None Remove="Classify8.Tests\**" />
  </ItemGroup>
</Project>